### ISSUE TITLE
AGP 3.2.0-alpha18 Error

### ISSUE THREAD

**Issue by benwicks** [ajalt/reprint#34]
```
error processing /Users/bwicks/.gradle/caches/transforms-1/files-1.1/reprint_spass-3.2.1.aar/cefecf9272366b1595138cd6fb920b26/jars/libs/pass-v1.1.4.jar
java.lang.ArrayIndexOutOfBoundsException: 5
	at org.objectweb.asm.ClassReader.readFrameType(ClassReader.java:2310)
	at org.objectweb.asm.ClassReader.readFrame(ClassReader.java:2269)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1448)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:144)
	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyzeJar(DesugaringClassAnalyzer.java:92)
	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:63)
	at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.lambda$getInitalGraphData$4(DesugarIncrementalTransformHelper.java:150)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

There are no errors when I build with AGP 3.1.3 stable.

**Comment by ajalt** [comment]
I'll take a look, but Reprint doesn't use any Java 8 features, so if desugaring fails, it's probably an Android Studio bug. I'm pretty sure that the samsung SDK is built with a very old compiler, so that might be the trigger.

**Comment by ajalt** [comment]
I'm able to build the sample app successfully using AS 3.2.0-beta1, so it looks like the AS bug has been fixed. Let me know if it pops up again.
