### ISSUE TITLE
NoClassDefFoundError CancellationSignal

### ISSUE THREAD

**Issue by nicolasSchirmer** [ajalt/reprint#41]
On the migration of the lib to Android X core, there was a conflict of dependencies .

https://developer.android.com/reference/kotlin/androidx/core/os/CancellationSignal

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/os/CancellationSignal;
        at com.github.ajalt.reprint.core.ReprintInternal.authenticate(ReprintInternal.java:95)
        at com.github.ajalt.reprint.core.Reprint.authenticate(Reprint.java:109)
        at com.github.ajalt.reprint.core.Reprint.authenticate(Reprint.java:90)
```

```
 Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.os.CancellationSignal" on path: DexPathList[[zip file "/data/app/...... "],nativeLibraryDirectories=[/data/app/.....==/lib/arm, /data/app/......==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.github.ajalt.reprint.core.ReprintInternal.authenticate(ReprintInternal.java:95) 
        at com.github.ajalt.reprint.core.Reprint.authenticate(Reprint.java:109) 
        at com.github.ajalt.reprint.core.Reprint.authenticate(Reprint.java:90) 
```

**Comment by ajalt** [comment]
This seems to be a problem with androidx 1.0.0. I updated to the latest version and it appears to be fixed. Can you try the snapshot build and let me know if it works? You can just change your reprint version number to `-SNAPSHOT`. e.g. `compile 'com.github.ajalt.reprint:core:-SNAPSHOT@aar'

**Comment by nicolasSchirmer** [comment]
Not solved, the exception still occurs

**Comment by ajalt** [comment]
Ah, ok. If you're using appcompat, then you should stick to Reprint 3.2.1. You only need to upgrade to reprint 3.3.0 if you use androidx.
